### ISSUE TITLE
Can DCGM exporter exposes container level GPU usage?

### ISSUE THREAD

**Issue by Cherishty** [NVIDIA/gpu-monitoring-tools#14]
Following the guide in DCGM exporter and demo in [here](https://docs.nvidia.com/datacenter/kubernetes-install-guide/index.html#kubernetes-setup-monitoring%5D), I only find that it does can expose GPU usage on node level.
My question is, can it expose GPU usage on container level ?
If so , how can we access that?

**Comment by guptaNswati** [comment]
Right now, there is no straight forward way to get container level GPU metrics because k8s doesn't expose this information except some tricks are still possible, like docker inspect of the running containers to identify NVIDIA DEVICES or kubectl describe pod or exec to get device information. For upstream k8s, there is effort going on to bring device-to-pod mapping feature https://docs.google.com/document/d/166Lb8oa7vAlNw3L59UpG7dohOHB7j40LDGVz68T5UaE/edit?usp=sharing

https://docs.google.com/document/d/166Lb8oa7vAlNw3L59UpG7dohOHB7j40LDGVz68T5UaE/edit?usp=sharing

In KONG, we actually share device ids in the API server, so if you do kubectl proxy and query the http API, you will see  devices in the pod spec. 

`kubectl proxy --port=8000 &
curl -s http://localhost:8000/api/v1/pods`
