### ISSUE TITLE
Broken Link to Prom Exporter

### ISSUE THREAD

**Issue by ajcollett** [NVIDIA/gpu-monitoring-tools#71]
Not sure where things are going, but the below link is used in a few places to point to the GPU node exporter here, and it's broken:

https://github.com/NVIDIA/gpu-monitoring-tools/tree/master/exporters/prometheus-dcgm#node_exporter

That is, in your own readme and in node-exporters repo. I am wondering what the new "workflow" is to use this with Prometheus?

**Comment by HuaizhengZhang** [comment]
Same question

**Comment by BaldStrong** [comment]
Same question

**Comment by c0nsaw** [comment]
Why is it so hard to find instructions on how to install dcgm exporter on a baremetal host

**Comment by RenaudWasTaken** [comment]
Hello!

I cleaned up the repo and product to be a lot simpler to use. If you aren't interested in moving to the v2 I've created a branch called v1 that still has the documentation (though all links are broken because at the time we didn't use permalinks).

The new workflow with prometheus is now documented on the readme: https://github.com/NVIDIA/gpu-monitoring-tools#quickstart-on-kubernetes

On versioning, we are still currently at a release candidate stage (RC), but are already using the software in production in the context of GPU Operator. Expect RC to be here for at least 2-3 months, I'm thinking of making the G.A of the 2.0.0 version match the next version of DCGM.

Hope this clears up any issue!
